CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  role VARCHAR(30) NOT NULL
);

CREATE TABLE hotels (
  hotel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_name VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  description TEXT,
  rating DECIMAL(2,1)
);

CREATE TABLE rooms (
  room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT NOT NULL,
  room_type VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  availability BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_rooms_hotels FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id)
);

CREATE TABLE bookings (
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(30) NOT NULL,
  CONSTRAINT fk_bookings_users FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_bookings_rooms FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

CREATE TABLE payments (
  payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL UNIQUE,
  amount DECIMAL(10,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  payment_status VARCHAR(30) NOT NULL,
  CONSTRAINT fk_payments_bookings FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
);

INSERT INTO users (name, email, password, phone, role) VALUES
('Demo Customer', 'customer@demo.com', 'password', '9876543210', 'CUSTOMER'),
('Hotel Manager', 'manager@demo.com', 'password', '9876500000', 'MANAGER'),
('Admin User', 'admin@demo.com', 'password', '9876511111', 'ADMIN');

INSERT INTO hotels (hotel_name, location, description, rating) VALUES
('Ocean Pearl', 'Goa', 'Beachside hotel with sea view rooms.', 4.7),
('Metro Grand', 'Bengaluru', 'Business hotel near the technology corridor.', 4.6),
('Heritage Inn', 'Jaipur', 'Traditional hotel for family stays.', 4.4);

INSERT INTO rooms (hotel_id, room_type, price, availability) VALUES
(1, 'Deluxe Sea View', 5800.00, TRUE),
(1, 'Standard Queen', 3200.00, TRUE),
(2, 'Executive Suite', 7200.00, TRUE),
(3, 'Royal Family Room', 4900.00, FALSE);
